services:
  lines:
    build: .
    container_name: lines
    restart: unless-stopped
    volumes:
      - lines-data:/app/data
    labels:
      - "traefik.http.services.lines.loadbalancer.server.port=3003"
    networks:
      - traefik-proxy

volumes:
  lines-data:

networks:
  traefik-proxy:
    external: true
